### ISSUE TITLE
terrarium tv features request

### ISSUE THREAD

**Issue by fenil123** [NitroXenon/Terrarium-Public#1]
Dear developer your app is really good, but it can be the best app to watch tv shows and movies by adding some extra features. The first feature I would like to see is WIFI sharing Which is found on Cinemaboxhd app. The last feature I would like to see is built in media player like vlc or others Which is also found on Cinemaboxhd app and Showbox. I think with this features your app will be an compleat app.

**Comment by NitroXenon** [comment]
I'll try to implement these features. Thanks for the recommendations. :D
