### ISSUE TITLE
OpenSubtitles.org require link

### ISSUE THREAD

**Issue by opensubtitles** [NitroXenon/Terrarium-Public#18]
Hi OS admin here,

please insert clickable link to your homepage, thats all what we got you are supporting our service.

Please read our implementation guide and follow it

Thank you

[1] http://trac.opensubtitles.org/projects/opensubtitles/wiki/DevReadFirst#Implementingopensubtitles.orgsupport

**Comment by NitroXenon** [comment]
Hello. Thanks for getting in touch. I'll try to fulfill all the requirements. Do you have an email so I can contact you privately? Thank you.

**Comment by opensubtitles** [comment]
hi @NitroXenon  sure, my email is admin [at] opensubtitles dot org
