### ISSUE TITLE
Crash on Firestick after screensaver

### ISSUE THREAD

**Issue by Sarkie** [NitroXenon/Terrarium-Public#19]
I think this happens when it comes out of sleep mode.

I'm not sure there's anything you can do about it.

![image](https://user-images.githubusercontent.com/283203/31619007-6097847a-b28b-11e7-9347-0364f85780b3.png)

**Comment by NitroXenon** [comment]
Thanks for the crash log. It seems to be a bug on Fire OS 5.1.1. Updating your OS should solve this issue.

**Comment by Sarkie** [comment]
Latest version afaik for first gen
