### ISSUE TITLE
关于 Android TV 的支持

### ISSUE THREAD

**Issue by Love4Taylor** [NitroXenon/Terrarium-Public#4]
无法在 Android TV 上正常使用, 包括选择剧集, 选择 season 以及后续的播放

**Comment by NitroXenon** [comment]
下個版本 (1.4.0) 將會加入 Android TV 遙控器 D-Pad 的支援

**Comment by NitroXenon** [comment]
如果你有看 Terrarium TV 的 Facebook 專頁你應該會知道... 我先關閉 issue.
