### ISSUE TITLE
建议反馈

### ISSUE THREAD

**Issue by Love4Taylor** [NitroXenon/Terrarium-Public#7]
去掉选中后返回 再进设置 依旧是选中状态

**Comment by Love4Taylor** [comment]
还有 就是 "播放" 等这些文字的翻译必须杀死APP进程才能改变 而其他部分直接返回退出重开即可
![](http://ww4.sinaimg.cn/large/0060lm7Tgy1fdclot7luoj31401z4wjr.jpg)

**Comment by Love4Taylor** [comment]
希望能内置 Chrome Custom tabs 来打开 IMDB 而不是弹到系统浏览器

**Comment by NitroXenon** [comment]
謝謝您的建議！Custom Tabs 未來的版本將會加入，不過好像只支援 Android 4.1 或以上的機型。

**Comment by Specher** [comment]
你好  我是你的粉丝 你的博客为啥不更新了 很期待你分享你的动态和一些技术

**Comment by Love4Taylor** [comment]
@NitroXenon 选择默认播放选项 似乎在新版失效了？
